name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - 'renovate/**'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-slim
    needs:
      - build
      - lint
    steps:
      - run: 'echo 1'

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '22']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn

      - run: npx tsc

      - run: yarn build

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '22']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn

      - run: npx prettier --check .

      - run: yarn lint
